from app.core.config import get_config

CONFIDENCE_SEND_THRESHOLD = 0.55
CONFIDENCE_SKIP_THRESHOLD = 0.25
ESCALATE_THRESHOLD = 0.35

MAX_CONTEXT_CHARS = 2000
MAX_HISTORY_MESSAGES = 6
MAX_CHUNK_CHARS = 400

RETRIEVAL_TOP_K = 8
RETRIEVAL_SCORE_THRESHOLD = 0.30
RERANKER_TOP_N = 5

__all__ = [
    'CONFIDENCE_SEND_THRESHOLD',
    'CONFIDENCE_SKIP_THRESHOLD',
    'ESCALATE_THRESHOLD',
    'MAX_CONTEXT_CHARS',
    'MAX_HISTORY_MESSAGES',
    'MAX_CHUNK_CHARS',
    'RETRIEVAL_TOP_K',
    'RETRIEVAL_SCORE_THRESHOLD',
    'RERANKER_TOP_N',
]
